# Based on buster slim - Debian 10 - https://hub.docker.com/_/microsoft-dotnet-core-runtime/ with .net core 3.1 runtime.
FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
COPY . /app
WORKDIR /app

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["dotnet", "Cloud.Core.NotificationHub.dll"]
